# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RN8818' do
  use_frameworks!

  # Pods for RN8818
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'MBProgressHUD'
  #pod 'LKDBHelper', '~> 2.4.2'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'MJRefresh'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftTTPageController'

  ###第三方平台
  pod 'Bugly'

  pod 'mob_sharesdk'
  pod 'mob_sharesdk/ShareSDKUI'
  pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
  pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
  pod 'mob_sharesdk/ShareSDKExtension'

end
